// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCmFdp9Inu2fcJavUn7BRGL2jqj6l1RTc',
    appId: '1:908843670295:web:119c2cf0b3f86419097552',
    messagingSenderId: '908843670295',
    projectId: 'moviles8schristian',
    authDomain: 'moviles8schristian.firebaseapp.com',
    storageBucket: 'moviles8schristian.appspot.com',
    measurementId: 'G-04RZPDGGQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNaOTaSIxXgfKGi5WHtmiovcXdOa7wRwc',
    appId: '1:908843670295:android:f5bc44ecb7e905c5097552',
    messagingSenderId: '908843670295',
    projectId: 'moviles8schristian',
    storageBucket: 'moviles8schristian.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4kCSZJ_6cn8SAzLE-11J4Q0Hvd2bHfLY',
    appId: '1:908843670295:ios:147fbda000ecbc57097552',
    messagingSenderId: '908843670295',
    projectId: 'moviles8schristian',
    storageBucket: 'moviles8schristian.appspot.com',
    iosBundleId: 'com.example.reto1DonetAppChristianRodriguez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4kCSZJ_6cn8SAzLE-11J4Q0Hvd2bHfLY',
    appId: '1:908843670295:ios:147fbda000ecbc57097552',
    messagingSenderId: '908843670295',
    projectId: 'moviles8schristian',
    storageBucket: 'moviles8schristian.appspot.com',
    iosBundleId: 'com.example.reto1DonetAppChristianRodriguez',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCmFdp9Inu2fcJavUn7BRGL2jqj6l1RTc',
    appId: '1:908843670295:web:e7c8c16fa799e04f097552',
    messagingSenderId: '908843670295',
    projectId: 'moviles8schristian',
    authDomain: 'moviles8schristian.firebaseapp.com',
    storageBucket: 'moviles8schristian.appspot.com',
    measurementId: 'G-RT96NSLLSB',
  );

}